### ISSUE TITLE
electronize build /target osx

### ISSUE THREAD

**Issue by srameh** [robalexclark/SilveR#1]
Hello Robin,
I came across your answer helping someone with electron.manifest.json. I used your answers and it worked great.
I have a couple of questions for you. I hope you dont mind.
1- How do you build a installer package for Mac OS using "electronize build /target osx"?
2- Do you need to run this on a Mac or can this be generated on Windows?

Thanks in advance!

**Comment by robalexclark** [comment]
Hello, 
For mac you do need to run it on macos to generate the installer (.dmg) file. If you don't have a mac (I do but it is very very old and slow so I don't use it much) you can use a free Azure Devops account to build on osx and build the installers for you. If you want to see the azure devops pipeline config take a look at azure-pipeline.yml in the root folder of this repository. This pipeline runs tests and if these pass it then builds installers for win,linux and osx.

**Comment by srameh** [comment]
Thank you Robin. I truly appreciate it. I am going to try the Azur Devops account. 

Thank you again.
